# Generated by Django 3.1.5 on 2021-01-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
