# Generated by Django 3.1.5 on 2021-01-21 06:42
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210120_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='createdAt',
            field=models.DateField(
                auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
