export const  ADD_POST_REQUEST = "ADD_POST_REQUEST"
export const  ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const  ADD_POST_FAIL = "ADD_POST_FAIL"
export const  ADD_REPLY = "ADD_REPLY"

export const  DELETE_POST_REQUEST = "DELETE_POST_REQUEST"
export const  DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const  DELETE_POST_FAIL = "DELETE_POST_FAIL"
export const  DELETE_REPLY = "DELETE_REPLY"

export const  DELETE_BOOKMARKS_REQUEST = "DELETE_BOOKMARKS_REQUEST"
export const  DELETE_BOOKMARKS_SUCCESS = "DELETE_BOOKMARKS_SUCCESS"
export const  DELETE_BOOKMARKS_FAIL = "DELETE_BOOKMARKS_FAIL"
export const  CLEAR_BOOKMARKS = "DELETE_BOOKMARKS_FAIL"

export const  GET_BOOKMARKS_REQUEST = "GET_BOOKMARKS_REQUEST"
export const  GET_BOOKMARKS_SUCCESS = "GET_BOOKMARKS_SUCCESS"
export const  GET_BOOKMARKS_FAIL = "GET_BOOKMARKS_FAIL"

export const  GET_POSTS_REQUEST = "GET_POSTS_REQUEST"
export const  GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const  GET_POSTS_FAIL = "GET_POSTS_FAIL"
export const  CLEAR_GET_POSTS = "CLEAR_GET_POSTS"

export const  GET_USER_POSTS_REQUEST = "GET_USER_POSTS_REQUEST"
export const  GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS"
export const  GET_USER_POSTS_FAIL = "GET_USER_POSTS_FAIL"

export const  GET_LIKED_POSTS_REQUEST = "GET_LIKED_POSTS_REQUEST"
export const  GET_LIKED_POSTS_SUCCESS = "GET_LIKED_POSTS_SUCCESS"
export const  GET_LIKED_POSTS_FAIL = "GET_LIKED_POSTS_FAIL"

export const  GET_USER_LIKED_POSTS_REQUEST = "GET_USER_LIKED_POSTS_REQUEST"
export const  GET_USER_LIKED_POSTS_SUCCESS = "GET_USER_LIKED_POSTS_SUCCESS"
export const  GET_USER_LIKED_POSTS_FAIL = "GET_USER_LIKED_POSTS_FAIL"

export const  ADD_POST = "ADD_POST"
export const  DELETE_POST = "DELETE_POST"

export const  GET_TAGS_REQUEST = "GET_TAGS_REQUEST"
export const  GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS"
export const  GET_TAGS_FAIL = "GET_TAGS_FAIL"

export const  GET_TAG_POSTS_REQUEST = "GET_TAG_POSTS_REQUEST"
export const  GET_TAG_POSTS_SUCCESS = "GET_TAG_POSTS_SUCCESS"
export const  GET_TAG_POSTS_FAIL = "GET_TAG_POSTS_FAIL"

export const  GET_POST_DETAILS_REQUEST = "GET_POST_DETAILS_REQUEST"
export const  GET_POST_DETAILS_SUCCESS = "GET_POST_DETAILS_SUCCESS"
export const  GET_POST_DETAILS_FAIL = "GET_POST_DETAILS_FAIL"

export const  POST_ACTION_REQUEST = "POST_ACTION_REQUEST"
export const  POST_ACTION_SUCCESS = "POST_ACTION_SUCCESS"
export const  POST_ACTION_FAIL = "POST_ACTION_FAIL"