export const  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const  USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const  USER_LOGOUT = "USER_LOGOUT"

export const  USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const  USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const  USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const  USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const  USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const  USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

export const  UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const  UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const  UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"
export const  UPDATE_PROFILE = "UPDATE_PROFILE"

export const  UPDATE_INFO_REQUEST = "UPDATE_INFO_REQUEST"
export const  UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS"
export const  UPDATE_INFO_FAIL = "UPDATE_INFO_FAIL"

export const  UPDATE_PERSONAL_IMAGE_REQUEST = "UPDATE_PERSONAL_IMAGE_REQUEST"
export const  UPDATE_PERSONAL_IMAGE_SUCCESS = "UPDATE_PERSONAL_IMAGE_SUCCESS"
export const  UPDATE_PERSONAL_IMAGE_FAIL = "UPDATE_PERSONAL_IMAGE_FAIL"

export const  VISIT_PROFILE_REQUEST = "VISIT_PROFILE_REQUEST"
export const  VISIT_PROFILE_SUCCESS = "VISIT_PROFILE_SUCCESS"
export const  VISIT_PROFILE_FAIL = "VISIT_PROFILE_FAIL"

export const  UPDATE_COVER_IMAGE_REQUEST = "UPDATE_COVER_IMAGE_REQUEST"
export const  UPDATE_COVER_IMAGE_SUCCESS = "UPDATE_COVER_IMAGE_SUCCESS"
export const  UPDATE_COVER_IMAGE_FAIL = "UPDATE_COVER_IMAGE_FAIL"

export const  GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST"
export const  GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS"
export const  GET_NOTIFICATIONS_FAIL = "GET_NOTIFICATIONS_FAIL"

export const  MAKE_RELATION = "MAKE_RELATION_REQUEST"
export const  CHANGE_PRIVACY = "CHANGE_PRIVACY"
export const  CHANGE_MESSAGES_PRIVACY = "CHANGE_MESSAGES_PRIVACY"


export const  GET_FOLLOW_NOTIFICATIONS_REQUEST = "GET_FOLLOW_NOTIFICATIONS_REQUEST"
export const  GET_FOLLOW_NOTIFICATIONS_SUCCESS = "GET_FOLLOW_NOTIFICATIONS_SUCCESS"
export const  GET_FOLLOW_NOTIFICATIONS_FAIL = "GET_FOLLOW_NOTIFICATIONS_FAIL"

export const  CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const  CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const  CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL"

export const  RELATION_REQUEST = "RELATION_REQUEST"
export const  RELATION_SUCCESS = "RELATION_SUCCESS"
export const  RELATION_FAIL = "RELATION_FAIL"

export const  GET_BLOCKS_REQUEST = "GET_BLOCKS_REQUEST"
export const  GET_BLOCKS_SUCCESS = "GET_BLOCKS_SUCCESS"
export const  GET_BLOCKS_FAIL = "GET_BLOCKS_FAIL"
export const  REMOVE_BLOCK = "REMOVE_BLOCK"


export const  SEARCH_USERS_REQUEST = "SEARCH_USERS_REQUEST"
export const  SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS"
export const  SEARCH_USERS_FAIL = "SEARCH_USERS_FAIL"

export const  GET_SUGGETIONS_REQUEST = "GET_SUGGETIONS_REQUEST"
export const  GET_SUGGETIONS_SUCCESS = "GET_SUGGETIONS_SUCCESS"
export const  GET_SUGGETIONS_FAIL = "GET_SUGGETIONS_FAIL"

export const  GET_ROOMS_REQUEST = "GET_ROOMS_REQUEST"
export const  GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS"
export const  GET_ROOMS_FAIL = "GET_ROOMS_FAIL"

export const  ACCESS_ROOM_REQUEST = "ACCESS_ROOM_REQUEST"
export const  ACCESS_ROOM_SUCCESS = "ACCESS_ROOM_SUCCESS"
export const  ACCESS_ROOM_FAIL = "ACCESS_ROOM_FAIL"

export const  ADD_RELATION_REQUEST = "ADD_RELATION_REQUEST"
export const  ADD_RELATION_SUCCESS = "ADD_RELATION_SUCCESS"
export const  ADD_RELATION_FAIL = "ADD_RELATION_FAIL"


export const  FOLLOW_USER = "FOLLOW_USER"

