# Generated by Django 3.1.5 on 2021-01-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210116_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followes',
            new_name='followers',
        ),
    ]
