# Generated by Django 3.1.5 on 2021-01-18 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20210116_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocks',
            field=models.ManyToManyField(blank=True, related_name='blocked_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='api.Tweet'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pupblic_messages',
            field=models.BooleanField(default=False),
        ),
    ]
