# Generated by Django 3.1.5 on 2021-01-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210118_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pupblic_messages',
            new_name='public_messages',
        ),
    ]
