# Generated by Django 3.1.5 on 2021-01-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210123_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_image',
            field=models.ImageField(default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
