# Generated by Django 3.1.7 on 2021-03-19 06:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210315_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='account.png', null=True, upload_to=accounts.models.cover_image_name),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.personal_image_name),
        ),
    ]
