# Generated by Django 3.1.7 on 2021-03-25 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20210319_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, related_name='follow_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
